services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=proposta-app'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    # volumes:
    #   - ./db.sql:/docker-entrypoint-initdb.d/db.sql
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'